# Generated by Django 2.0.5 on 2018-05-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atApt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='date',
            new_name='appointment_date',
        ),
    ]
