# Generated by Django 2.0.5 on 2018-05-23 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atApt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atApt.Appointments')),
            ],
        ),
    ]
