# Generated by Django 2.0.5 on 2018-05-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atApt', '0003_users_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.CharField(max_length=255),
        ),
    ]
