# Generated by Django 2.0.5 on 2018-05-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atApt', '0004_auto_20180524_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joiner',
            new_name='Join',
        ),
    ]
