# Generated by Django 2.0.5 on 2018-05-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atApt', '0005_auto_20180524_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='staff_user',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='user',
        ),
        migrations.AddField(
            model_name='appointments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='atApt.Users'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='staff_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to='atApt.Users'),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
